version: "3"

networks:
  prusa:

volumes:
  grafana_data:
  prusa_syslog_logs:

services:
  loki:
    image: grafana/loki:2.9.6
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./docs/examples/config/on_premise/loki.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - prusa

  agent:
    image: grafana/agent:v0.40.3
    container_name: agent
    restart: unless-stopped
    ports:
      - "10007:10007/udp"
    volumes:  
      - type: bind
        source: ./docs/examples/config/on_premise/agent.river
        target: /etc/agent-config/agent.river
    environment:
      - AGENT_MODE=flow
    entrypoint:
      - /bin/grafana-agent
      - run
      - /etc/agent-config/agent.river
    networks:
      - prusa

  grafana:
    image: grafana/grafana:10.4.1
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=grafana-xyzchart-panel, grafana-polystat-panel
    depends_on:
      - loki
    ports:
      - "3000:3000"
    networks:
      - prusa
    volumes:
      - ./docs/examples/config/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
      - ./docs/examples/grafana/provisioning:/var/lib/grafana/dashboards