exporter:
  scrape_timeout: 1000 # scrape timeout of Prusa Link in ms
  log_level: info
  remote_write:
    enabled: true
    format: prometheus # can be also influx
    #endpoint: http://influxproxy:8007/api/v1/push/influx/write
    endpoint: http://mimir:9009/api/v1/push
  prusalink:
    enabled: false
  syslog:
    metrics:
      enabled: true
      listen_address: 0.0.0.0:10008
    logs:
      enabled: false
      listen_address: 0.0.0.0:10007
      directory: /var/log/prusa
      filename: exporter.log
      max_size: 10 # in MB
      max_age: 7 # in days
      max_backups: 10
